Crystal Dunn:
  enabled: true,
  preferredPosition: null
Tobin Heath:
  enabled: true,
  preferredPosition: null
Lindsey Horan:
  enabled: true,
  preferredPosition: null
Mallory Pugh:
  enabled: true,
  preferredPosition: null
Kelly O'Hara:
  enabled: true,
  preferredPosition: null
Julie Johnston:
  enabled: true,
  preferredPosition: null
Becky Sauerbrunn:
  enabled: true,
  preferredPosition: null
Abby Dahlkemper:
  enabled: true,
  preferredPosition: null
Megan Rapinoe:
  enabled: true,
  preferredPosition: null
Carli Lloyd:
  enabled: true,
  preferredPosition: null
